# Generated by Django 4.2 on 2023-10-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_mer', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Get_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_info_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nut_sufficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=7)),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nut_sufficient_save', to='api.dog_info')),
            ],
        ),
        migrations.CreateModel(
            name='Nut_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nut_name', models.CharField(max_length=100)),
                ('actual_num', models.FloatField()),
                ('percent', models.IntegerField()),
                ('min_num', models.FloatField()),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nut_report', to='api.dog_info')),
            ],
        ),
        migrations.CreateModel(
            name='Nut_7_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A10100', models.FloatField()),
                ('A10300', models.FloatField()),
                ('A10400', models.FloatField()),
                ('A10600', models.FloatField()),
                ('A10700', models.FloatField()),
                ('suffient', models.IntegerField()),
                ('lack', models.IntegerField()),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nut_7_save', to='api.dog_info')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.ManyToManyField(related_name='food_month', to='api.dog_info')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_result', to='api.dog_info')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='api.dog_info')),
            ],
        ),
    ]
