# Generated by Django 4.2 on 2023-10-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Item_En',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items_en', to='api.dog_info')),
            ],
        ),
    ]
