# Generated by Django 4.2 on 2023-05-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
