# Generated by Django 4.2 on 2023-06-04 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_mer', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Food_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='food_item',
            name='dog_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='api.dog_info'),
        ),
    ]
