# Generated by Django 4.2 on 2023-06-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_food_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_Post',
            new_name='Get_Id',
        ),
    ]
