# Generated by Django 4.2 on 2023-10-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_food_post_get_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nut_sufficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=100)),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nut_sufficient_save', to='api.dog_info')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items1', to='api.dog_info')),
                ('food_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items2', to='api.dog_info')),
                ('food_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items3', to='api.dog_info')),
                ('food_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items4', to='api.dog_info')),
            ],
        ),
    ]
