# Generated by Django 4.2 on 2023-10-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_nut_sufficient_monthly_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_food',
            name='dog_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_month', to='api.dog_info'),
        ),
        migrations.CreateModel(
            name='Nut_some_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B10100', models.FloatField()),
                ('B10300', models.FloatField()),
                ('B10700', models.FloatField()),
                ('dog_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nut_some_save', to='api.dog_info')),
            ],
        ),
    ]
