# Generated by Django 4.2 on 2023-10-18 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_monthly_food_dog_info_nut_some_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_food',
            name='food_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items1', to='api.food_item'),
        ),
        migrations.AlterField(
            model_name='monthly_food',
            name='food_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items2', to='api.food_item'),
        ),
        migrations.AlterField(
            model_name='monthly_food',
            name='food_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items3', to='api.food_item'),
        ),
        migrations.AlterField(
            model_name='monthly_food',
            name='food_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items4', to='api.food_item'),
        ),
    ]
