# Generated by Django 4.1.7 on 2023-05-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_activity_remove_user_age_remove_user_bcs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("minimum_value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("actual_value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("new_field", models.CharField(max_length=100)),
            ],
        ),
    ]
