# Generated by Django 4.1.7 on 2023-05-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_nutrient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Nutrient",
        ),
    ]
