# Generated by Django 4.2 on 2023-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
