# Generated by Django 4.1 on 2023-08-06 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_image', models.ImageField(default='default_profile.png', upload_to='profile_images')),
                ('location', models.CharField(blank=True, default='', max_length=30)),
                ('company', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('weight', models.CharField(max_length=30)),
                ('bcs', models.IntegerField()),
                ('improve', models.CharField(blank=True, max_length=30)),
                ('disease', models.CharField(blank=True, max_length=30)),
                ('sex', models.IntegerField(choices=[(0, '중성'), (1, '암컷'), (2, '수컷')])),
                ('activity', models.IntegerField(choices=[(0, '매우 얌전함'), (1, '조금 얌전함'), (2, '보통'), (3, '조금 활발함'), (4, '매우 활발함')])),
                ('weight_control', models.IntegerField(choices=[(0, '매우 감량'), (1, '조금 감량'), (2, '유지'), (3, '조금 증량'), (4, '매우 증량')])),
                ('food_cycle', models.IntegerField(choices=[(0, '없음'), (1, '1주'), (2, '1달'), (3, '1년')], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/posts/images')),
                ('hashtag', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog_Food_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_token', models.IntegerField()),
                ('dog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dog_food_token', to='user.dog')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dog_food_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
