# Generated by Django 4.1 on 2023-05-03 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bcs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='user',
            name='improve',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='species',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight_control',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=30)),
                ('activity', models.CharField(max_length=100)),
                ('weight_control', models.CharField(max_length=30)),
                ('bcs', models.IntegerField()),
                ('cycle', models.CharField(blank=True, max_length=30)),
                ('improve', models.CharField(blank=True, max_length=30)),
                ('disease', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
