# Generated by Django 3.2.16 on 2023-05-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_activity_remove_user_age_remove_user_bcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
