# Generated by Django 4.1 on 2023-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_company_alter_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='cycle',
        ),
        migrations.AddField(
            model_name='dog',
            name='food_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dog',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight_control',
            field=models.IntegerField(),
        ),
    ]
