# Generated by Django 4.1 on 2023-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_dog_cycle_dog_food_cycle_dog_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='activity',
            field=models.IntegerField(choices=[(0, '매우 얌전함'), (1, '조금 얌전함'), (2, '보통'), (3, '조금 활발함'), (4, '매우 활발함')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='food_cycle',
            field=models.IntegerField(choices=[(0, '없음'), (1, '1주'), (2, '1달'), (3, '1년')], default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.IntegerField(choices=[(0, '중성'), (1, '암컷'), (2, '수컷')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight_control',
            field=models.IntegerField(choices=[(0, '매우 감량'), (1, '조금 감량'), (2, '유지'), (3, '조금 증량'), (4, '매우 증량')]),
        ),
    ]
