# Generated by Django 4.2 on 2023-07-01 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_dog_activity_alter_dog_food_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_Food_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_token', models.IntegerField()),
                ('dog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dog_food_token', to='user.dog')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dog_food_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
