# Generated by Django 4.2 on 2023-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_dog_food_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_habit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_place',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_profit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
