# Generated by Django 4.2 on 2023-10-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.IntegerField()),
                ('dog_info', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_1', models.IntegerField()),
                ('food_2', models.IntegerField()),
                ('food_3', models.IntegerField()),
                ('food_4', models.IntegerField()),
                ('dog_info', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nut_7_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_info', models.IntegerField()),
                ('A10100', models.FloatField()),
                ('A10300', models.FloatField()),
                ('A10400', models.FloatField()),
                ('A10600', models.FloatField()),
                ('A10700', models.FloatField()),
                ('suffient', models.IntegerField()),
                ('lack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nut_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_info', models.IntegerField()),
                ('nut_name', models.CharField(max_length=100)),
                ('actual_num', models.FloatField()),
                ('percent', models.FloatField()),
                ('min_num', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nut_some_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_info', models.IntegerField()),
                ('B10100', models.FloatField()),
                ('B10300', models.FloatField()),
                ('B10700', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nut_sufficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_info', models.IntegerField()),
                ('token_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.ManyToManyField(to='algorithm_api.food')),
            ],
        ),
    ]
