# Generated by Django 4.2 on 2023-10-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_food',
            old_name='dog_info',
            new_name='month_id',
        ),
    ]
