# Generated by Django 4.2 on 2023-10-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm_api', '0002_rename_dog_info_monthly_food_month_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_info', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/foods/images')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Item_En',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dog_info', models.IntegerField()),
            ],
        ),
    ]
