# Generated by Django 4.2 on 2023-07-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm_api', '0002_rename_dog_info_food_item_dog_info_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_item',
            old_name='dog_info_id',
            new_name='dog_info',
        ),
        migrations.RenameField(
            model_name='nut_7_save',
            old_name='dog_info_id',
            new_name='dog_info',
        ),
        migrations.RenameField(
            model_name='nut_report',
            old_name='dog_info_id',
            new_name='dog_info',
        ),
    ]
